name: CI
on:
  push:
    branches: [ main, 'feat/*' ]
    paths:
      - 'src/**'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  - DOTNET_NO_LOGO: true
  - DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    needs: version
    uses: ./.github/workflows/reusable_build.yml
    with:
      package: false

  format:
    uses: ./.github/workflows/reusable_format.yml
