on:
  workflow_call:
    inputs:
      configuration:
        description: 'dotnet build configuration'
        default: 'Release'
        required: false
        type: string

      package:
        description: 'dotnet pack and upload'
        required: true
        type: boolean

      package-version:
        description: 'if $package, the version'
        required: false
        type: string

      package-artifact-name:
        description: 'if $package, what to name the artifact'
        default: 'packages'
        required: false
        type: string

env:
  CONFIGURATION: ${{ inputs.configuration }}
  DOTNET_NO_LOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    name: build-linux
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        
      - name: dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
          cache: true
          cache-dependency-path: |
            src/LIS.LIS01A2/packages.lock.json
            src/LIS.LIS02A2/packages.lock.json

      - name: restore locked deps
        run: dotnet restore --locked-mode

      - name: build
        run: dotnet build --no-restore --configuration $CONFIGURATION

      - name: pack
        if: ${{ inputs.package }}
        run: |
          dotnet pack \
            --no-build \
            --configuration $CONFIGURATION \
            -p:Version="${{ inputs.package-version }}" \
            --output ./packages

      - name: upload nupkg
        if: ${{ inputs.package }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.package-artifact-name }}
          path: ./packages/*.nupkg
