on:
  workflow_call:

env:
  - DOTNET_NO_LOGO: true
  - DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            3.x
            6.x
            8.x
          cache: true

      - name: ensure formatting
        run: |
          dotnet format --verify-no-changes --no-restore -v:diag --exclude ~/.nuget
