on:
  workflow_call:

env:
  CONFIGURATION: ${{ inputs.configuration }}
  DOTNET_NO_LOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
          cache: true
          cache-dependency-path: |
            src/LIS.LIS01A2/packages.lock.json
            src/LIS.LIS02A2/packages.lock.json

      - name: restore locked deps
        run: dotnet restore --locked-mode

      - name: ensure formatting
        run: |
          dotnet format --verify-no-changes --no-restore -v:diag --exclude ~/.nuget
